### Get Centers
GET http://localhost:4000/api-alidar/centers
Authorization: Bearer <accessToken>

### Get Center/:id
GET http://localhost:4000/api-alidar/centers/:centerId
Authorization: Bearer <accessToken>

### Update Center/:id
PATCH http://localhost:4000/api-alidar/centers/:centerId
Content-Type: application/json
Authorization: Bearer <accessToken>

# Request body (optional)
{
    "name": "example",
    "email": "example@example.com",
    "password": "klsal123rds?",
    "phone": "092879213",
    "street": "Example street",
    "zone": "Example zone",
    "numberDoor": "4310",
    "departament": "Example departament",
    "description": "Example description",
    "numberVolunteersRequired": 0,
    "onboardingStepPosition": 1,
    "photo": "string_base64"
}

### Delete Center/:id
DELETE http://localhost:4000/api-alidar/centers/:centerId
Authorization: Bearer <accessToken>
