### Create Center Food /:centerId/:foodId
POST http://localhost:4000/api-alidar/centers/:centerId/foods
Content-Type: application/json
Authorization: Bearer <accessToken>

# Request body (required)
{
    "name": "Example food",
    "category": "Example category",
    "amount": 12,
    "unitMeasurement": "KG"
}

### Get Foods
GET http://localhost:4000/api-alidar/centers/:centerId/foods
Authorization: Bearer <accessToken>

### Get Center foods /:centerId/foods/:foodId
GET http://localhost:4000/api-alidar/centers/:centerId/foods/:foodId
Authorization: Bearer <accessToken>

### Update Center food /:centerId/foods/:foodId
PATCH http://localhost:4000/api-alidar/centers/:centerId/foods/:foodId
Content-Type: application/json
Authorization: Bearer <accessToken>

# Request body (optional)
{
    "category": "Example category",
    "amount": 12,
    "unitMeasurement": "ML"
}

### Delete Center food /:centerId/foods/:foodId
DELETE http://localhost:4000/api-alidar/centers/:centerId/foods/:foodId
Authorization: Bearer <accessToken>

