export const departments = [
  {
    name: 'Montevideo',
    zones: [
      'Barrio Artigas',
      'Belvedere',
      'Cabaña Anaya',
      'Camino El Tapir',
      'Casabó',
      'Ciudad Vieja',
      'Cordón',
    ],
  },
  {
    name: 'Canelones',
    zones: [
      'Aguas Corrientes',
      'Atlántida',
      'Barrios Blancos',
      'Ciudad de la Costa',
      'La Floresta',
      'Las Piedras',
      'Toledo',
    ],
  },
  {
    name: 'Maldonado',
    zones: [
      'Punta del este',
      'Piriápolis',
      'San carlos',
      'Pan de azúcar',
      'Garzon',
      'Aiguá',
      'Solis grande',
    ],
  },
  {
    name: 'San José',
    zones: [
      'Barrio Lahmann',
      'Barrio Rohrmoser',
      'Barrio Amón',
      'Barrio Escalante',
      'Barrio Don Bosco',
      'Barrio México',
    ],
  },
  {
    name: 'Artigas',
    zones: [
      'Aceguá',
      'Arbolito',
      'Arévalo',
      'Bañado de Medina',
      'Centurión',
      'Cerro de las Cuentas',
      'Fraile Muerto',
    ],
  },
  {
    name: 'Colonia',
    zones: [
      'Real de san carlos',
      'Colonia del sacramento',
      'Piedra de los indios',
      'Paso de la horqueta',
      'Minas de marancio',
      'La estanzuela',
      'Ombúes de lavalle',
    ],
  },
  {
    name: 'Salto',
    zones: [
      'San antonio',
      'Guaviyu',
      'Salto grande',
      'Colonia Lavalleja',
      'Constitucion',
      'Laureles',
      'Pueblo fernandez',
    ],
  },
  {
    name: 'Soriano',
    zones: [
      'Cardona',
      'Palmitas',
      'José Enrique Rodó',
      'Dolores',
      'Mercedes',
      'Palmitas',
      'Chacra de dolores',
    ],
  },
  {
    name: 'Florida',
    zones: [
      'Piedra alta',
      'Corralón del tigre y Santa Hania',
      'San fernando',
      'Villa maria',
      'La calera',
      'San cono',
      'Burastero',
    ],
  },
  {
    name: 'Flores',
    zones: [
      'Trinidad',
      'Ismael Cortinas',
      'Andresito',
      'La casilla',
      'Juan jose castro',
      'Cerro colorado',
      'Área rural',
    ],
  },
  {
    name: 'Rivera',
    zones: [
      'Vichadero',
      'Tranqueros',
      'Minas de corrales',
      'Cerro Marconi',
      'Misiones-Siñeriz',
      'Cerro Caqueiro',
      'Magisterial',
    ],
  },
  {
    name: 'Lavalleja',
    zones: [
      'José batlle y Ordoñez',
      'Mariscala',
      'José Pedro Varela',
      'Solis de mataojo',
      'Minas',
      'Pirarajá',
      'Zapicán',
    ],
  },
  {
    name: 'Rocha',
    zones: [
      'Valizas',
      'La pedrera',
      'Lascano',
      'Chuy',
      'La paloma',
      'Cebollatí',
      'La coronilla',
    ],
  },
  {
    name: 'Durazno',
    zones: [
      'Sarandí del yí',
      'La paloma',
      'Carmen',
      'Centenario',
      'Santa Bernardina',
      'Blanquillo',
      'Durazno',
    ],
  },
  {
    name: 'Tacuarembó',
    zones: [
      'Ansina',
      'Paso de los toros',
      'San gregorio de polanco',
      'Las toscas',
      'Tambores',
      'Curtina',
      'Punta de carretera',
      'Paso bonilla',
    ],
  },

  {
    name: 'Rio negro',
    zones: [
      'Fray bentos',
      'Young',
      'Nuevo Berlín',
      'San javier',
      'Algorta',
      'Barrio anglo',
      'Grecco',
    ],
  },

  {
    name: 'Paysandú',
    zones: [
      'Chapicuy',
      'Guichón',
      'Lorenzo geyres',
      'Quebracho',
      'Piedras coloradas',
      'Tambores',
      'Porvenir',
    ],
  },

  {
    name: 'Cerro largo',
    zones: [
      'Acegúa',
      'Arévalo',
      'Melo',
      'Fraile muerto',
      'Rio branco',
      'Tupambae',
      'Isidoro noblia',
    ],
  },
  {
    name: 'Treinta y tres',
    zones: [
      'Cerro chato',
      'Treinta y tres',
      'Vergara',
      'Villa sara',
      'General enrique martinez',
      'Rincon',
      'Santa clara de olimar',
    ],
  },
]

export const donators = [
  {
    name: 'Michael',
    lastName: 'Flores',
    email: 'michaelflores@gmail.com',
    password: 'michael1?',
  },
  {
    name: 'Maylen',
    lastName: 'Valdez',
    email: 'maylenvaldez@gmail.com',
    password: 'maylen1?',
  },
  {
    name: 'Lucia',
    lastName: 'Sebe',
    email: 'luciasebe@gmail.com',
    password: 'lucia1?',
  },
  {
    name: 'Nachito',
    lastName: 'Ibarra',
    email: 'nachoibarra@gmail.com',
    password: 'nachito1?',
  },
  {
    name: 'Emir',
    lastName: 'Romero',
    email: 'emirromero@gmail.com',
    password: 'emir1?',
  },
]

export const centers = [
  {
    name: 'Chakarita fubol clu',
    email: 'chakarita@center.com',
    password: 'chakarita1?',
    phone: '234567764565',
    street: 'Av 18 de julio',
    numberDoor: '1232',
    description:
      'Somos un centro deportivo y a su vez, busca poder llegarle alimentos a personas necesitadas',
    zone: 'Centro',
    departament: 'Montevideo',
    numberVolunteersRequired: 10,
    foods: [
      {
        amount: Math.floor(Math.random() * 100),
        unitMeasurement: 'KG',
        name: 'Arroz',
        category: 'No perecederos',
      },
      {
        amount: Math.floor(Math.random() * 100),
        unitMeasurement: 'KG',
        name: 'Fideo',
        category: 'No perecederos',
      },
      {
        amount: Math.floor(Math.random() * 100),
        unitMeasurement: 'KG',
        name: 'Pulpa de tomate',
        category: 'No perecederos',
      },
    ],
  },
  {
    name: 'ANIMA',
    email: 'anima@center.com',
    password: 'anima1?',
    phone: '345634',
    street: 'Canelones',
    numberDoor: '3535',
    description:
      'Instituto educativo con las orientaciones ADM y TIC con inserción en el mundo laboral a nuestros estudiantes',
    zone: 'Centro',
    departament: 'Montevideo',
    numberVolunteersRequired: 12,
    foods: [
      {
        amount: Math.floor(Math.random() * 100),
        unitMeasurement: 'KG',
        name: 'Arroz',
        category: 'No perecederos',
      },
      {
        amount: Math.floor(Math.random() * 100),
        unitMeasurement: 'KG',
        name: 'Pulpa de tomate',
        category: 'No perecederos',
      },
    ],
  },
  {
    name: 'Manos juntas',
    email: 'manosjuntas@center.com',
    password: 'manosjuntas1?',
    phone: '1232',
    street: 'Av Italia',
    numberDoor: '53654',
    description: 'Centro colaborativo fundado por vecinos del barrio',
    zone: 'Cordon',
    departament: 'Montevideo',
    numberVolunteersRequired: 5,
    foods: [
      {
        amount: Math.floor(Math.random() * 100),
        unitMeasurement: 'KG',
        name: 'Polenta',
        category: 'No perecederos',
      },
    ],
  },
  {
    name: 'Flores',
    email: 'flores@center.com',
    password: 'flores1?',
    phone: '46645',
    street: 'San martin',
    numberDoor: '0043',
    zone: 'Cerrito',
    departament: 'Montevideo',
    numberVolunteersRequired: 8,
  },
  {
    name: 'Centro gruta',
    email: 'centrogruta@center.com',
    password: 'centrogruta1?',
    phone: '09876',
    street: 'Gruta de lourdes',
    numberDoor: '3121232',
    zone: 'Casavalle',
    departament: 'Montevideo',
    foods: [
      {
        amount: Math.floor(Math.random() * 100),
        unitMeasurement: 'KG',
        name: 'Harina',
        category: 'No perecederos',
      },
    ],
  },
]
